FROM node:14

ENV GOOGLE_APPLICATION_CREDENTIALS="/usr/local/etc/gcloud/application_default_credentials.json"

WORKDIR /var/www

# COPY package*.json .
# COPY ["package.json", "package-lock.json", "./"]
COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3002

CMD ["npm", "run", "dev"]